package pkgfinal;
interface  hotellist {
    public String hotel [][]={{"PAKJING","EAST Beijing" ,"Jianguo Hotel Beijing" ," The Great Wall Hotel Beijing",""},
                       {"SHANGHAI","New World Shanghai Hotel", "Fairmont Peace Hotel" , "Swissotel Grand Shanghai",""},
                       {"HONG KONG","Harbour Grand Hong Kong","M1 Hotel North Point" ,"iclub Fortress Hill Hotel",""},
                       {"CHONGQING","InterContinental Chongqing", "Hilton Chongqing Hotel" , "Chongqing Marriott Hotel",""},
                       {"MOSCOW","Vega Hotel & Convention Center" , "The Ritz-Carlton Moscow", "Aquamarine Hotel", "Legendary Hotel Sovietsky"},
                       {"ST.PETERSBURG", "Crowne Plaza St. Petersburg" , "City Park Apartments", "Salut plus","" },
                       {"KAZAN","Riviera, Hotel Mano", "Grand Hotel Kazan","",""},
                       {"BREMEN","Ural Hotel Perm","","",""},
                       {"BANGALORE","Shangri-La's - Eros Hotel", "New Delhi ITC Maurya", "a Luxury Collection Hotel", ""},
                       {"NEW DELHI", "OYO 8937 Ragu Residency" ,"Hotel Chenthur Park" , "Challenger Residency","" },
                       {"BANKOK", "The Okura Prestige" , "Villa Mungkala" , "Amara Bangkok",""},
                       {"PHUKET","Horizon Karon Beach Resort & Spa" , "Baan Malinee Bed and Breakfast","",""},
                       {"CHIANG MAI","The 51 Hometel", "Mövenpick Suriwongse Hotel","","" },
                       {"NAYPYDAW","PARKROYAL Nay Pyi Taw" , "Hilton Nay Pyi Taw" , "Apex Hotel",""},
                       {"YANGON", "Lotte Hotel" ,  "Pan Pacific","",""},
                       {"KUALA LUMPUR", "Best Western Petaling Jaya", "Berjaya Times Square Hotel", "Kuala Lumpur" ,"Fraser Residence Kuala Lumpur"},
                       {"MUKAH","Kingwood Resort" ,"Li Hua Hotel","",""},
                       {"MANILA", "Armada Hotel" ,"Solaire Resort and Casino", "Fairmont Makati",""},
                       {"DAVAO","Grand Regal Hotel Davao", "Orange Grove Hotel","",""},
                       {"HO CHI MINH","Sunland Hotel" ,"Park Hyatt Saigon","",""},
                       {"DA NANG","Samdi Hotel","Grandvrio City Danang","",""},
                       {"JAKARTA", "The Sultan Hotel Jakarta" , "Gran Melia Jakarta" , "Four Points by Sheraton Jakarta Thamrin"  ,""},
                       {"SURABAYA","Amaris Hotel Margorejo - Surabaya" , "favehotel Graha Agung Surabaya" ,"Best Western Papilio Hotel",""},
                       {"NARITA","The Prince Gallery Tokyo Kioicho", "A Luxury Collection Hotel" , "Apa Hotel And Resort Tokyo Bay Makuhari", "Grand Nikko Tokyo Daiba"},
                       {"HIROSHIMA","Hotel Sunroute Hiroshima" , "Hotel Granvia" , "APA Hotel Hiroshima-Ekimae",""},
                       {"SOUL","JW Marriott Dongdaemun" , "Square Four Points By Sheraton Seoul","","" },
                       {"BUSAN","Lotte Hotel The BS Hotel","","",""},
                       {"PYONGYANG","","","",""},
                       {"PHNOM PENH", "G Mekong Hotel" , "Sunway Hotel Phnom Penh","",""  },
                       {"DUSHANBE","Sheraton Dushanbe Hotel" , "Dushanbe Serena Hotel","",""},
                       {"TASHKENT", "Yyldyz Hotel" ,"Nusay Hotel","","" },
                       {"ASHGABAT","","","",""},
                       {"DHAKA","Innotel Luxury Business Hotel","Best Western La Vinci Hotel","",""},
                       {"THIMPHU","Taj Tashi 17,848  Hotel Osel",  "Khamsum Inn Ariya Hotel","",""},
                       {"KATHMANDU", "Hotel Shambala", "Hotel Moonlight OYO 105 Hotel Travel Inn","",""}
    };
    public int cht[][]={{0,3215,4820,5610,0},
                        {0,3795,4120,7890,0},
                        {0,7840,6750,2390,0},
                        {0,3480,3475,4500,0},
                        {0,4570,5120,7510,4520},
                        {0,4755,5420,4785,0},
                        {0,4820,3150,0,0},
                        {0,3175,0,0,0},
                        {0,7840,4890,4855,0},
                        {0,5420,3450,2500,0},
                        {0,3480,1690,2000,0},
                        {0,2000,2100,0,0},
                        {0,3120,2900,0,0},
                        {0,1980,1880,2000,0},
                        {0,2450,3150,0,0},
                        {0,2500,2620,2490,2820},
                        {0,2000,2150,0,0},
                        {0,2780,3500,3100,0},
                        {0,2550,2450,0,0},
                        {0,3100,3215,0,0},
                        {0,3420,2950,0,0},
                        {0,2150,3520,3150,0},
                        {0,3150,3800,2190,0},
                        {0,2905,3150,2900,4000},
                        {0,3150,3480,3495,0},
                        {0,3480,3590,0,0},
                        {0,4580,0,0,0},
                        {0,0,0,0,0},
                        {0,2500,2980,0,0},
                        {0,3000,2580,0,0},
                        {0,3150,3950,0,0},
                        {0,0,0,0,0},
                        {0,3480,1690,2000,0},
                        {0,1850,2400,2400,0},
                        {0,2580,2690,2520,0},                   
    };
    
}
